import {Inter} from 'next/font/google'
import {ReactNode} from "react";
import {Providers} from "@/app/store";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Home',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: ReactNode
}) {
    return (
        <html lang="en">
        <Providers>
            <body className={inter.className}>{children}</body>
        </Providers>
        </html>
    )
}
